### PR TITLE
Added Elbit systems to the table

### PR DESCRIPTION
**Pull request by Tzahile**

### CODE REVIEW

**Comment by Tzahile** [comment]
@nsxr51

**Comment by JonathanDn** [comment]
@Tzahile Great to have you. please put your entry in a sorted alphabetically number and bump +1 the total counter on the top

**Comment by JonathanDn** [comment]
@nsxr51 If you would want ot update the PR that could also work - and have Elbit join in no time :)

**Comment by Tzahile** [comment]
Done :+1:

**Review by JonathanDn — APPROVED** [review]

**Comment by JonathanDn** [comment]
Welcome :)

**Pull request merged**
