### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Enghouse-CCSP-PS**
Added Enghouse Interactive row

### CODE REVIEW

**Comment by eranshmil** [comment]
Thanks for your contribution!
Can you please update the counter at the top of the table?

**Comment by Enghouse-CCSP-PS** [comment]
Sure. Thanks

**Comment by Enghouse-CCSP-PS** [comment]
@eranshmil  Any chance to get it approved? Enghouse still not appear on the list.

**Review by Enghouse-CCSP-PS — COMMENTED** [review]
fix the total

**Review by JonathanDn — APPROVED** [review]
Welcome :)

**Pull request merged**
