### PR TITLE
Added RELE.AI

### PR DESCRIPTION
**Pull request by elonsalfati**

### CODE REVIEW

**Comment by JonathanDn** [comment]
Hey @ElonSalfati  glad to recieve this PR! could you bump the "total companies" counter by 1 please and update me so I can merge this PR?

**Comment by JonathanDn** [comment]
@ElonSalfati
That is awesome, but remove the 2 companies from the end as they are duplicates (growers and ozcode) 
They are in their spot alphabetically now.

Also put your entry alphabetically

**Comment by JonathanDn** [comment]
@ElonSalfati  - Total counter was updated by new addition so please +1 the latest

**Comment by adi-works** [comment]
@ElonSalfati Can you rebase it?

**Pull request closed without merging**
