### PR TITLE
add daily.dev to the list

### PR DESCRIPTION
**Pull request by idoshamun**
Hey!

I would like to add daily.dev.
Our extension is written in Vue 2

### CODE REVIEW

**Comment by JonathanDn** [comment]
@idoshamun Just trying to understand a few small things.

Your a business product? will potentially hire devs in the future?

**Comment by idoshamun** [comment]
Yes, we are an official company registered here in Israel under the name Daily Dev Ltd.
We're growing fast so I believe we can expect to hire devs in the future

**Comment by JonathanDn** [comment]
Awesome, good luck with the business and welcome to the list ;)
* Further, feel free to add more commpanies that work with Vue if you hear of them or meet them.
* And also if you see something you think can improve the list experience - please do open an issue/PR, and happy sukkot!

**Review by JonathanDn — APPROVED** [review]

**Comment by idoshamun** [comment]
You bet! Thanks a bunch :)

**Pull request merged**
